[package]
name = "shrimply-editor-state"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown.workspace = true
shrimply-profiling = { workspace = true }
shrimply-manim-state = { workspace = true }
shrimply-math-core = { workspace = true }
shrimply-preferences-core = { workspace = true }
shrimply-project-document = { workspace = true, default-features = true }
shrimply-preview-provider-skia = { workspace = true }
shrimply-process-reporting = { workspace = true }
tracing.workspace = true
uuid.workspace = true
