[package]
name = "shrimply-render-3d-metal"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[build-dependencies]
shrimply-slang-build = { path = "../../slang-build" }

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-foundation.workspace = true
objc2-metal.workspace = true
shrimply-asset = { path = "../../asset" }
shrimply-render-3d = { path = "../render-3d" }
shrimply-render-metal = { path = "../../render-metal" }
shrimply-scene-3d = { path = "../scene-3d" }
