[package]
name = "shrimply-playback-performance"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel.workspace = true
rangemap.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
shrimply-math-core = { workspace = true }
shrimply-math-media = { workspace = true }
shrimply-project-document = { workspace = true, default-features = true }
shrimply-preview-provider-skia = { workspace = true }
tracing.workspace = true
uuid.workspace = true
