[package]
name = "shrimply-video-core"
version = "0.1.0"
edition = "2024"

[features]
cuda-stabilization = ["dep:shrimply-affine-l1-stabilization"]

[dependencies]
shrimply-paint-skia = { path = "../../paint/paint-skia" }
shrimply-math-geometry = { path = "../../math/geometry" }
shrimply-math-core = { path = "../../math/core" }
shrimply-preview-skia = { path = "../../preview/preview-skia" }
shrimply-core = { path = "../../core" }
shrimply-background = { path = "../../background" }
uuid.workspace = true
shrimply-math-media = { path = "../../math/media" }
shrimply-render-core = { path = "../../render-core" }
shrimply-evaluation = { path = "../../evaluation" }
shrimply-video-modifiers = { path = "../video-modifiers" }
shrimply-math-color = { path = "../../math/color" }
shrimply-asset = { path = "../../asset" }
shrimply-blender = { path = "../../blender/blender-bridge" }
shrimply-layered-image = { path = "../../layered-image/layered-image" }
shrimply-affine-l1-stabilization = { path = "../../stabilization/affine-l1-stabilization", optional = true }
shrimply-mesh-flow-stabilization = { path = "../../stabilization/mesh-flow-stabilization" }
cached.workspace = true
tracing.workspace = true
cairo = { workspace = true, features = ["freetype"] }
glam.workspace = true
glib.workspace = true
pango = { workspace = true, features = ["v1_57"] }
pangocairo.workspace = true
shrimply-project = { path = "../../project/project" }
shrimply-server-client = { path = "../../server-client" }
shrimply-text-3d = { path = "../../3d/text-3d" }
shrimply-shape-3d = { path = "../../3d/shape-3d" }
shrimply-render-3d = { path = "../../3d/render-3d" }
shrimply-scene-3d = { path = "../../3d/scene-3d" }
shrimply-transform-3d = { path = "../../3d/transform-3d" }
shrimply-3dgs = { path = "../../3d/3dgs" }
skia-safe = { workspace = true, features = ["textlayout", "svg"] }
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
shrimply-resource-pipeline = { path = "../../resource-pipeline" }
vtracer.workspace = true
hashbrown.workspace = true
num-traits.workspace = true
rusqlite = { workspace = true, features = ["bundled"] }
png.workspace = true
tempfile.workspace = true
