[package]
name = "shrimply-3dgs-metal"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[build-dependencies]
shrimply-slang-build = { path = "../../slang-build" }

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-foundation.workspace = true
objc2-metal.workspace = true
shrimply-asset = { path = "../../asset" }
shrimply-3dgs = { path = "../3dgs" }
shrimply-render-metal = { path = "../../render-metal" }
