[package]
name = "shrimply-export-gtk"
version = "0.1.0"
edition = "2024"

[dependencies]
adw.workspace = true
glam.workspace = true
gtk.workspace = true
shrimply-export-core = { path = "../export-core" }
shrimply-math-core = { path = "../../math/core" }
shrimply-math-media = { path = "../../math/media" }
shrimply-project = { path = "../../project/project" }
shrimply-state = { path = "../../state" }
shrimply-gtk-components = { path = "../../ui/gtk-components" }
tracing.workspace = true
