[package]
name = "shrimply-components-demo-core"
version = "0.1.0"
edition = "2024"

[dependencies]
rhai.workspace = true
shrimply-property-model = { workspace = true }
shrimply-math-interpolation = { workspace = true }
shrimply-keyframe-graph-skia = { workspace = true }
shrimply-math-core = { workspace = true }
shrimply-visual-modifiers = { workspace = true }
uuid.workspace = true
