[package]
name = "shrimply-tts"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { workspace = true, features = ["blocking"] }
rmp-serde.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_bytes.workspace = true
shrimply-asset = { path = "../../asset" }
shrimply-math-core = { path = "../../math/core" }
shrimply-server-client = { path = "../../server-client" }
tracing.workspace = true
tokio.workspace = true
