[package]
name = "shrimply-inspector-document"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json.workspace = true
shrimply-audio-modifiers = { workspace = true }
shrimply-property-model = { workspace = true }
shrimply-inspector-core = { workspace = true, default-features = false }
shrimply-math-core = { workspace = true }
shrimply-preview-provider-skia = { workspace = true }
shrimply-project-document = { workspace = true, default-features = true }
shrimply-visual-modifiers = { workspace = true }
uuid.workspace = true
