[package]
name = "shrimply-compute-client"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { workspace = true, features = ["serde"] }
reqwest = { workspace = true, features = ["blocking", "query"] }
rmp-serde.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_bytes.workspace = true
shrimply-math-geometry = { workspace = true }
tracing.workspace = true
tokio.workspace = true
uuid = { workspace = true, features = ["v4"] }
