[package]
name = "shrimply-inspector-appkit"
version = "0.1.0"
edition = "2024"

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-app-kit = { workspace = true, features = ["objc2-uniform-type-identifiers"] }
objc2-foundation.workspace = true
objc2-uniform-type-identifiers = "0.3.2"
block2.workspace = true
shrimply-components-appkit = { path = "../components-appkit" }
shrimply-preview-metal = { path = "../../preview/preview-metal" }
shrimply-inspector-core = { path = "../inspector-core", default-features = false }
shrimply-math-color = { path = "../../math/color" }
shrimply-math-core = { path = "../../math/core" }
shrimply-project = { path = "../../project/project" }
shrimply-state = { path = "../../state" }
shrimply-tts = { path = "../../audio/tts" }
shrimply-timeline = { path = "../../timeline/timeline" }
shrimply-property-transfer = { path = "../../property-transfer" }
serde_json.workspace = true
