[package]
name = "shrimply-keyframe-graph-skia"
version = "0.1.0"
edition = "2024"

[dependencies]
shrimply-discrete-keyframe-graph-skia = { workspace = true }
shrimply-cross-ui-theme = { workspace = true }
shrimply-math-interpolation = { workspace = true }
shrimply-math-core = { workspace = true }
shrimply-math-color = { workspace = true }
shrimply-math-geometry = { workspace = true }
glam.workspace = true
skia-safe = { workspace = true, features = ["gl", "textlayout"] }
shrimply-components-skia = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
