[package]
name = "shrimply-export-cuda"
version = "0.1.0"
edition = "2024"

[target.'cfg(not(target_os = "macos"))'.dependencies]
ffmpeg-next.workspace = true
shrimply-export-core = { path = "../export-core" }
shrimply-math-core = { path = "../../math/core" }
shrimply-project = { path = "../../project/project" }
shrimply-video-cuda = { path = "../../video/video-cuda" }
