[package]
name = "shrimply-components-appkit"
version = "0.1.0"
edition = "2024"

[target.'cfg(target_os = "macos")'.dependencies]
block2.workspace = true
objc2.workspace = true
objc2-app-kit.workspace = true
objc2-core-graphics.workspace = true
objc2-foundation.workspace = true
shrimply-component-core = { path = "../component-core" }
shrimply-component-metal = { path = "../component-metal" }
shrimply-cross-ui-theme = { path = "../cross-ui-theme" }
shrimply-interpolation = { path = "../../interpolation" }
shrimply-keyframe-graph-core = { path = "../../timeline/keyframe-graph-core" }
shrimply-math-color = { path = "../../math/color" }
shrimply-math-core = { path = "../../math/core" }
uuid.workspace = true
