[package]
name = "shrimply-components-demo-appkit"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "shrimply-components-demo-appkit"
path = "src/main.rs"

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-app-kit.workspace = true
objc2-foundation.workspace = true
shrimply-benchmarking = { path = "../../benchmarking" }
shrimply-component-core = { path = "../component-core" }
shrimply-components-appkit = { path = "../components-appkit" }
shrimply-components-demo-core = { path = "../components-demo-core" }
shrimply-cross-ui-theme = { path = "../cross-ui-theme" }
shrimply-keyframe-graph-core = { path = "../../timeline/keyframe-graph-core" }
shrimply-math-color = { path = "../../math/color" }
shrimply-support = { path = "../../support" }

