[package]
name = "shrimply-math-media"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown.workspace = true
glam = { workspace = true, features = ["serde"] }
num-traits.workspace = true
serde = { workspace = true, features = ["derive"] }
shrimply-math-interpolation = { workspace = true }
shrimply-math-color = { workspace = true }
shrimply-math-core = { workspace = true }
shrimply-math-geometry = { workspace = true }
shrimply-project-types = { workspace = true }
shrimply-render-core = { workspace = true }
