[package]
name = "shrimply-paint-model"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
shrimply-asset = { workspace = true }
shrimply-paint-interpolation = { workspace = true }
shrimply-timeline-value = { workspace = true }
shrimply-math-color = { workspace = true }
shrimply-math-geometry = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
