[package]
name = "shrimply-export-metal"
version = "0.1.0"
edition = "2024"

[target.'cfg(target_os = "macos")'.dependencies]
ffmpeg-next.workspace = true
shrimply-export-core = { workspace = true, default-features = true }
shrimply-math-core = { workspace = true }
shrimply-preview-render-metal = { workspace = true }
shrimply-project-document = { workspace = true, default-features = true }
tracing.workspace = true
