[package]
name = "shrimply-preview-render-core"
version = "0.1.0"
edition = "2024"

[dependencies]
shrimply-pdf = { workspace = true }
shrimply-paint-skia = { workspace = true }
shrimply-audio-engine = { workspace = true }
shrimply-render-core = { workspace = true }
ffmpeg-next.workspace = true
skia-safe = { workspace = true, features = ["svg", "textlayout"] }
shrimply-project-document = { workspace = true, default-features = true }
shrimply-manim-state = { workspace = true }
shrimply-project-evaluation = { workspace = true }
shrimply-math-core = { workspace = true }
shrimply-math-media = { workspace = true }
shrimply-background = { workspace = true }
uuid.workspace = true
tracing.workspace = true
shrimply-preview-provider-skia = { workspace = true }
shrimply-visual-core = { workspace = true }
shrimply-visual-modifiers = { workspace = true }
shrimply-math-geometry = { workspace = true }
shrimply-math-color = { workspace = true }
shrimply-loading-screen-skia = { workspace = true }
shrimply-i18n = { workspace = true }
shrimply-layered-image-loader = { workspace = true }
shrimply-scene-3d = { workspace = true }
shrimply-manim-wgpu = { workspace = true }
glam.workspace = true
